#!/bin/sh

set -e

# Generate version information from git release tag

./scripts/git-version > VERSION

# To satisfy automake
git log > ChangeLog

# Bootstrap autotools
autoreconf --verbose --force --install

rm -rf autom4te.cache
rm -f config.h.in~

