.\"
.\" buildd-uploader.1 - the *roff document processor source for the buildd-uploader manual
.\"
.\" This file is part of Debian GNU/Linux's prepackaged version of wanna-build.
.\" Copyright (C) 1998 James Troup <james@nocrew.org>.
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License , or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; see the file COPYING.  If not, write to
.\" the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH buildd-uploader 1 .\" "Command Manual" 1998-11-20 "November 20, 1998"
.SH NAME
buildd-uploader \- program to upload packages built by the buildd
.SH SYNOPSIS
.B buildd-uploader
.SH VERSION
This man page documents buildd-uploader from 1998-11-20.
.SH DESCRIPTION
\fBbuildd-uploader\fR uploads packages (with dupload) built by the
build daemon and notifies a wanna-build database of successful
uploads. \fBbuildd-uploader\fR is usually run from a cron job.
.PP
\fBbuildd-uploader\fR can be configured via /etc/buildd.conf or with
the builddconfig program.  In particular, the site dupload uploads to
can be changed and the means of accessing the wanna-build database.
.SS OPTIONS
\fBbuildd-uploader\fR takes no arguments.
.SH ENVIRONMENT VARIABLES
The following environment variables are used by \fBsbuild\fR:
.IP "HOME"
The home directory of the user.
.SH FILES
\fBbuildd-uploader\fR logs it's activities to ~/daemon.log.  It
protects against concurrent execution by locking the file
~/upload.lock.  ~/upload/ is the directory where files to upload are
looked for.
.SH DIAGNOSTICS
Diagnostics go to stderr and the log file.
.SH BUGS
None known at this time.
.PP
Email bug reports to
.BR buildd-disc@nocrew.org .
Be sure to include the word ``buildd-uploader'' somewhere in the ``Subject:'' field.
.SH AUTHOR
.nf
Roman Hodek
Roman.Hodek@informatik.uni-erlangen.de
.fi
.SH "SEE ALSO"
.SP
.BR buildd ( 1 ),
.BR dupload ( 1 ),
.BR buildd.conf ( 5 ),
.BR builddconfig ( 8 ).
