.\" Copyright © 1998       James Troup <james@nocrew.org>
.\" Copyright © 2005-2006  Roger Leigh <rleigh@debian.org>
.\"
.\" sbuild is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" sbuild is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston,
.\" MA  02111-1307  USA
.TH SBUILD 1 "9 Mar 2006" "Version 0.42" "Debian sbuild"
.SH NAME
sbuild \- build debian packages from source
.SH SYNOPSIS
.B sbuild
[ \-a/\-\-add-depends=<dependency-line> ] [ \-A/\-\-arch\-all ]
[ \-b/\-\-batch] [\-d/\-\-dist=<distribution> ] [ \-D/\-\-debug ]
[ \-f/\-\-force-depends=<dependency-line> ]
[ \-m/\-\-maintainer=<maintainer> ]
[ \-e/\-\-uploader=<uploader> ]
[ \-k/\-\-keyid=<key> ]
[ \-\-purge=<mode>] [\-s/\-\-source ] [ \-v/\-\-verbose ] [ \-q/\-\-quiet ]
[ \-\-make\-binNMU=<entry> ]
[ \-\-nolog ]
package-to-build_x.y-z(.dsc) [ ... ]
.SH VERSION
This man page documents the packaged version of sbuild.  This version
is maintained by the \fBbuildd-tools\fP project developers on Alioth
(\f[CR]https://alioth.debian.org/projects/buildd\-tools/\fP).
.PP
There is also a version maintained by Ryan Murray which is adapted to build
daemon needs, with similar functionality.  This version should be equally
capable of working in a buildd setup, but has a number of enhancements aimed at
making it suitable for use by end-users.
.SH DESCRIPTION
\fBsbuild\fR rebuilds Debian binary packages from the corresponding
Debian source.  It is similar to dbuild and debbuild, but, unlike
them, it knows about source dependencies.
.PP
\fBsbuild\fR can fetch the Debian source over a network, or it can use
locally available sources.
.PP
\fBsbuild\fR mails the build logs to a user.  It is configured by the
configuration files \fI/etc/sbuild.conf\fP,
\fI/etc/sbuild.conf.local\fP, and \fI~/.sbuildrc\fP.  An example
sbuildrc is available in
\fI/usr/share/doc/sbuild/examples/example.sbuildrc\fP.  \fBsbuild\fR
will \fBnot\fP run without a valid \fI~/.sbuildrc\fP.
.PP
Optionally, source dependencies are read from
\fI/var/lib/sbuild/source-dependencies-*\fP; see that file for more
information on source-dependencies.  Also see README.Debian.
.PP
You can build either using a local package with its .dsc file or a
remote one by specifying an explicit dpkg version.
.PP
Note: \fBsbuild\fR must be run in the directory (\fI~/build\fP by default) with
the chroot-{stable,testing,unstable} symlink to the chroot or it will do the
build in the base install which is not what you want.  When using schroot,
these requirements do not apply; the chroot having the name (or alias) of the
specified distribution will be used; schroot uses a chroot named
\fI$distribution-sbuild\fP, or \fI$distribution\fP, in that order of
preference.
.SH OPTIONS
.TP
.IR \-a , "--add-depends=<dependency-line>"
This option adds some source dependency information for a package. It
can be given more than one time with accumulating effect. The argument
is a line of source dependencies in the same format as in
\fI/var/lib/sbuild/source-dependencies\fR. The given dependencies are appended to
the src-deps from source-dependencies-* files or package src-deps, resp.
.TP
.IR \-A , "--arch-all"
Also build Architecture: all packages, i.e. use dpkg-buildpackage -b
instead of -B.
.TP
.IR \-b , "--batch"
Operate in batchmode, i.e. write a build-progress file during execution
and files on shutdown to facilitate a clean restart.
.TP
.IR \-d , "--distribution=<distribution>"
Fetch source packages from specified distribution.
.TP
.IR \-f , "--force-depends=<dependency-line>"
This option overrides source dependency information for a package. It
can be given more than one time with accumulating effect. The argument
is a line of source dependencies in the same format as in
\fI/var/lib/sbuild/source-dependencies\fR.
.TP
.IR \-D , "--debug"
Enable debug output.
.TP
.IR \-m , "--maintainer=<maintainer>"
Passed to dpkg-genchanges and is used to set the Maintainer: field in the .changes file(s).
.TP
.IR \-e , "--uploader=<maintainer>"
Passed to dpkg-genchanges and is used to set the Changed-by: field in the .changes file(s).
.TP
.IR \-k , "--keyid=<maintainer>"
Passed to dpkg-genchanges and is used to set the key to sign the .changes file(s).
Default is not using any key.
.TP
.IR \-n , "--nolog"
Do not create a package log file in the $log_dir directory and no
build log file, but print everything to stdout. Also do not send any
log mails.
.TP
.IR \-p , "--purge=<mode>"
\fImode\fR decides if to delete the build directory. Possible values
are \fBalways\fR, \fBnever\fR, and \fBsuccessful\fR.
.TP
.IR \-s , "--source"
Also build source package, i.e. use dpkg-buildpackage without -B. This
also switches on --purge=never.
.TP
.IR \-v , "--verbose"
Be verbose, i.e. all information goes to stdout as well as to the log files.
.TP
.IR \-q , "--quiet"
Be quiet.  This is the opposite of --verbose.
.TP
.IR "--make-binNMU=<entry>"
With this option, \fBsbuild\fR will create a new changelog entry in
debian/changelog of every package built. The version number will be in
the format for binary-only NMUs (three dotted parts in the Debian
revision); the maintainer is set to the maintainer name configured for
\fBsbuild\fR. The \fIentry\fR parameter will be used as a changelog
entry after a fixed one "Binary-only non-maintainer upload for ARCH --
no source changes". Please note that the versions in the
\fIpackage-to-build\fR arguments still have to be the unmodified
(non-NMU ones) so that sources can be found. The version number in log
files and mails will be modified by \fBsbuild\fR automatically.
.SH ENVIRONMENT VARIABLES
The following environment variables are used by \fBsbuild\fR:
.IP "HOME"
The home directory of the user.
.IP "LOGNAME"
Used in lockfiles.
.IP "sourcebase"
A URL for a Debian source distribution; generated by sbuild for scripts in source-dependencies.
.IP "binarybase"
A URL for a Debian binary distribution; generated by sbuild for scripts in source-dependencies.
.SH FILES
.TP
.I /etc/sbuild.conf
Global configuration, maintained by the sbuild maintainer.
.TP
.I /etc/sbuild.conf.local
Global configuration, maintained by the system administrator.  This
may be used to override the defaults in sbuild.conf.
.TP
.I ~/.sbuildrc
User specific configuration
.TP
.I /var/lib/sbuild
Build statistics, source dependencies and lock files.
.SH AUTHORS
Roman Hodek <Roman.Hodek@informatik.uni-erlangen.de>.
.PP
\fBsbuild\fR is based on debbuild, written by James Troup
<james@nocrew.org> and has been modified by
.nf
Ben Collins <bcollins@debian.org>,
Ryan Murray <rmurray@debian.org>,
Francesco Paolo Lovergine <frankie@debian.org>,
Michael Banck <mbanck@debian.org>, and
Roger Leigh <rleigh@debian.org>
.fi
.SH "SEE ALSO"
.BR update-sourcedeps (1),
.BR avg-pkg-build-time (1),
.BR schroot (1),
.BR sbuild-setup(7).
.\"#
.\"# The following sets edit modes for GNU EMACS
.\"# Local Variables:
.\"# mode:nroff
.\"# fill-column:79
.\"# End:
