debian/install/etc/buildd/buildd.conf		etc/buildd
debian/install/usr/bin/buildd*			usr/bin
debian/install/usr/share/man/man1/buildd*       usr/share/man/man1
debian/install/usr/share/man/man5/buildd*	usr/share/man/man5
debian/install/usr/share/man/man8/buildd*	usr/share/man/man8
debian/install/usr/share/perl5/Buildd*		usr/share/perl5
debian/install/var/lib/buildd			var/lib
etc/apt-keys/*.asc				usr/share/buildd
